### ISSUE TITLE
Manifest editor: hyphenated name should be warning, not error 

### ISSUE THREAD

**Issue by rombert** [puppetlabs/geppetto#9]
If I have a class named dev-utils, then gepetto marks it as an error. Since it's something that works, even though it's not recommended, it should be a warning, rather than an error.

![gepetto-manifest](https://f.cloud.github.com/assets/21237/1501441/a43c8f4a-488b-11e3-8411-8b62a2b5ccf7.png)

**Comment by binford2k** [comment]
Hyphenated names have been invalid Puppet code for quite some time now.
